name: sudoku
description: "Cross-Platform Sudoku Game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1
  count_up_flutter: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/icon/SudokuIcon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icon/SudokuIcon.png"
  windows:
    generate: true
    image_path: "assets/icon/SudokuIcon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/icon/SudokuIcon.png"
  remove_alpha_ios: true

flutter:
  assets:
    - assets/icon/SudokuIcon.png
    - assets/img/sudoku-bg-dark.png
    - assets/img/sudoku-bg-lite.png
  fonts:
    - family: "Montserrat"
      fonts:
        - asset: "assets/fonts/Montserrat-VariableFont_wght.ttf"
        - asset: "assets/fonts/Montserrat-Italic-VariableFont_wght.ttf"
          style: italic
    - family: "Inter"
      fonts:
        - asset: "assets/fonts/Inter-VariableFont_opsz,wght.ttf"
        - asset: "assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf"
          style: italic
  uses-material-design: true
