name: sudoku
description: "Cross-Platform Sudoku Game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  provider: ^6.1.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "icon/SudokuIcon.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "icon/SudokuIcon.png"
  windows:
    generate: true
    image_path: "icon/SudokuIcon.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "icon/SudokuIcon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
